[build]
builder = "nixpacks"
buildCommand = "npm run setup && npm run build"

[deploy]
startCommand = "sh -c 'npx prisma db push --accept-data-loss && npm run start'"
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
